<?xml version="1.0" encoding="UTF-8"?>
<?oxygen SCHSchema="http://openurc.org/ns/targetdesc-2"?>
<target about="http://hdm-stuttgart.de/TestTarget" id="TestTarget"
    xmlns="http://openurc.org/ns/targetdesc-2"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openurc.org/ns/targetdesc-2 http://openurc.org/ns/targetdesc-2 http://purl.org/dc/elements/1.1/ http://dublincore.org/schemas/xmls/qdc/2003/04/02/dc.xsd http://purl.org/dc/terms/ http://dublincore.org/schemas/xmls/qdc/2003/04/02/dcterms.xsd">
    <dcterms:conformsTo>http://openurc.org/ns/targetdesc-2/isoiec24752-4-2013</dcterms:conformsTo>
    <dc:publisher>http://hdm-stuttgart.de</dc:publisher>
    <dc:description/>
    <dc:creator/>
    <dc:rights/>
    <dc:contributor/>
    <socket id="TestSocket" name="http://hdm-stuttgart.de/TestTarget/TestSocket">
        <retrieveFrom>TestSocket.uis</retrieveFrom>
    </socket>
</target>
